CREATE TABLE users (
    ID SERIAL PRIMARY KEY,
    DISPLAY_NAME TEXT,
    AUTH_ID TEXT,
    IMG TEXT,
);

CREATE TABLE user_profile_info (
    ID SERIAL PRIMARY KEY,
    USER_ID INTEGER,
    USER_STATUS TEXT,
    EMAIL VARCHAR (40),
    PHONE VARCHAR (40),
    CITY VARCHAR (20),
    US_STATE VARCHAR (2),
    BOAT_INFO VARCHAR (40),
    ABOUT_ME VARCHAR (140),
);

CREATE TABLE member_applications (
    ID SERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR (20),
    LAST_NAME VARCHAR (20),
    EMAIL VARCHAR (40),
    CITY VARCHAR (30),
    US_STATE VARCHAR (2),
    ZIPCODE VARCHAR (5),
    BOAT_NAME VARCHAR (30),
    BOAT_TYPE VARCHAR (30),
    DATE_SUBMITTED VARCHAR (30)
);



